version: '3'
services:
    miimagen:
        image: athos54/miprimeraimagen:v4
        #build: .
        ports:
            - "80:80"
    mysql:
        image: mysql
        environment:
            - MYSQL_ROOT_PASSWORD=my-secret-pw
